//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public string empid { get; set; }
        public string empname { get; set; }
        public System.DateTime dob { get; set; }
        public System.DateTime doj { get; set; }
        public string location { get; set; }
    }
}
